baseurl = "https://sudojslee.github.io"
title = "JSLEE'S DEV BLOG"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Using utterances, so disable disqus
# disqusShortname = "yourdiscussshortname"

[params]
  author = "Junseok Lee"
  info = "Backend Developer, Open For Work"
  description = "Junseok Lee's dev blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
#   customSCSS = ["scss/custom.scss"]
#   customJS = ["js/custom.js"]

[params.goatCounter]
  code = "sudojslee" # You will access your account at https://[code].goatcounter.com

[params.utterances]
  repo = "sudojslee/sudojslee.github.io" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "utterances" # https://utteranc.es/#heading-issue-label
  theme = "preferred-color-scheme" # https://utteranc.es/#heading-theme

# [taxonomies]
#   category = "categories"
#   series = "series"
#   tag = "tags"
#   author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sudojslee/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/junseok-lee-4149b4162"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/dawdadda/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "https://www.linkedin.com/in/junseok-lee-4149b4162"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
